# fly.toml app configuration file generated for next-qr-code-generator-server on 2025-07-20T19:03:46+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'next-qr-code-generator-server'
primary_region = 'otp'

[build]
  dockerfile = 'Dockerfile.server'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
